### ISSUE TITLE
Update core.async deps

### ISSUE THREAD

**Issue by daniel-quintoandar** [TheClimateCorporation/squeedo#53]
The latest version is 1.3.610 but it requires the ancient 0.4.474.

Updating [may fix errors like](https://github.com/technomancy/slamhound/issues/81#issuecomment-56324828)
```
Syntax error macroexpanding clojure.core.async/go at (com/climate/squeedo/sqs_consumer.clj:34:7).
	at clojure.lang.Compiler.macroexpand1(Compiler.java:7010)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7093)
...
Caused by: java.lang.IllegalArgumentException: No implementation of method: :has? of protocol: #'clojure.core.cache/CacheProtocol found for class: clojure.core.memoize.PluggableMemoization
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
```

**Comment by jmelching** [comment]
Can you give an example of how to reproduce?

**Comment by daniel-quintoandar** [comment]
I'm not sure how to reproduce it :(
After running `start-consumer` and reloading the namespace (using the [vim-fireplace](https://github.com/tpope/vim-fireplace)), that error pops up on repl...
Updating it may not even resolve that problem (I'm not sure it is a problem on squeedo at all :thinking:), but the core.async version still a 2 years old dependency...

**Comment by jmelching** [comment]
I've pulled down the code and tested everything out in a repl and haven't been able to reproduce what you are seeing.  Probably a plugin or something you are using interfering.  I can try to update the deps and push a new version to see if that helps ya.
